kit_body_1 = {"name": "a"}
kit_body_2 = {"name": "a" * 511}
kit_body_3 = {"name": ""}
kit_body_4 = {"name": "a" * 512}
kit_body_5 = {"name": "Qwerty"}
kit_body_6 = {"name": "Мария"}
kit_body_7 = {"name": "!@#$%"}
kit_body_8 = {"name": "Человек и Компания"}
kit_body_9 = {"name": "123"}
kit_body_10 = {}
kit_body_11 = {"name": 123}